### ISSUE TITLE
REST result could not be parsed as JSON

### ISSUE THREAD

**Issue by ylihemmo** [Porssari/HomeAssistant-client#1]
HA integration not working. 

Getting this error in logs.:
2023-09-05 20:18:20.213 INFO (MainThread) [homeassistant.components.automation.porssari_ohjaustiedon_paivitys] Pörssäri-ohjaustiedon päivitys: Executing step Päivitä porssari_json
2023-09-05 20:18:20.305 WARNING (MainThread) [homeassistant.components.rest.sensor] REST result could not be parsed as JSON
2023-09-05 20:18:20.309 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.Metadata.Timestamp|default(0) }}'

Home Assistant 2023.8.4
Supervisor 2023.08.3
Frontend 20230802.1 - latest

Might be user error.

**Comment by tuokiv** [comment]
Vastaan nyt protokollan vastaisesti tähän suomeksi, kun ei tätä meidän systeemiä muualla voi käyttää.

Oletko lisännyt sen laitetunnuksen sinne input_text.porssari_mac -kentän arvoksi? Tuo virhe tulee jos kyselyyn ei palvelimelta palaudu vastausta, ja en keksi mikä muu sen voisi tehdä kuin puuttuva/virheellinen laitetunnus.

**Comment by ylihemmo** [comment]
Jep kyllä vaan.
400 koodin näyttää kysely palauttavan, mutta mistään logista en löydä mihin urliin kysely lähtee.
Jospa koitan vielä luoda uuden laitteen.

**Comment by tuokiv** [comment]
Varmista kanssa ettei siihen kenttään jää yhtään välilyöntiä tms alkuun tai loppuun. En tiedä voisiko semmoinenkin homeassistantissa aiheuttaa ongelmia. Jos vika oli tuossa, niin pitää selvitellä voisiko sen kentän arvon trimmata tuohon urliin vietäessä.

**Comment by ylihemmo** [comment]
Komentoriviltä ajettuna palauttaa kyllä mitä pitääkin, mutta jostain syystä automaation kautta ei vaan toimi.
Debuggi logituskaan ei tarjoa tuon enempää tietoa.

Palautuva data tuntuu kyllä tosiaan olevan ihan validia jsonia, mutta jostain syystä nyt HA ei sitä ymmärrä.
Tai sitten lähtevä kysely on väärässä muodossa...

**Comment by tuokiv** [comment]
En kykene toistamaan tuota virhettä, niin varmistaisin vielä:
- olet kopioinut semmoisenaan release-valikossa olevan porssari_core.yaml tekemättä siihen mitään muutoksia
- olet luonut laitteen Pörssärin sivustolle
- olet lisännyt laitetunnuksen HomeAssistantiin uudelleenkäynnistyksen jälkeen Asetukset --> Laitteet ja palvelut --> Auttajat --> Pörssäri laitetunnus

**Comment by ylihemmo** [comment]
Juuri näin olin tehnyt, mutta otinpa nyt vielä kertaalleen homman puhtaalta pöydältä (kolmannen kerran) tällä kertaa vielä buuttasin kaiken ja nyt rupesi homma toimimaan. Eli ilmeisesti oli evotusta. Kiitos ja anteeksi.

**Comment by tuokiv** [comment]
Hieno homma kun sait pelaamaan, ei anteeksipyydettävää!

Dokumentaatio kaipaa parannusta kyllä.
