### ISSUE TITLE
Kanavien mäppäys

### ISSUE THREAD

**Issue by jorkki22** [Porssari/HomeAssistant-client#3]
Laitoin pörssäriin 3 kanavaa ohjaukseen numeroilla 3,4 ja 8. HA puolelle ilmestyi aktiivisiksi kanavat numerot 1,2,3. 
Ajattelin ensin että tein jotain väärin asennuksessa, mutta uudelleen asennuksen jälkeen ilmiö toistui. 

Kokeilin lopuksi lisätä uuden ohjauksen kanavalle numero 5, niin HA ilmestyi kanava numero 4 aktiiviseksi. 

Onko tuossa kanavien mäppäyksessä jotain vikaa vai minulla konfiguraatio ongelma?

![image](https://github.com/user-attachments/assets/19c366fc-c6f5-4768-ba1a-f332be78119e)

**Comment by tuokiv** [comment]
Tämä vaatii bugikorjauksen. Eli nuo sivuston ohjauskanavat ei toteudu ellei kaikkia kanavia ole liitetty johonkin kuormaan.

Vian voi tilapäisesti korjata luomalla ylimääräinen ohjauskuorma, ja liittämällä siihen nuo tyhjäksi jäävät kanavat välistä.

**Comment by tuokiv** [comment]
Korjattu viimeisimmässä yaml-versiossa
